CREATE TABLE PET(
    id NUMERIC PRIMARY KEY AUTO_INCREMENT NOT NULL,
    userid NUMERIC,
    name VARCHAR,
    type VARCHAR,
    gender VARCHAR,
    hair VARCHAR
);

CREATE TABLE USER(
    id NUMERIC PRIMARY KEY AUTO_INCREMENT NOT NULL,
    email VARCHAR,
    password VARCHAR
);