CREATE TABLE PET(
    id NUMERIC PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR,
    type VARCHAR,
    gender VARCHAR
);

CREATE TABLE USER(
    id NUMERIC PRIMARY KEY AUTO_INCREMENT NOT NULL,
    email VARCHAR,
    password VARCHAR
);